attendance/attendance/apis/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework.urlpatterns import format_suffix_patterns
from .views import (
    StudentRegistarion,  
    SectionsViewSets, 
    EnrolledView,
    Login,
    Attend,
    Attend_Record
    )
app_name = 'apis'


route = routers.DefaultRouter()

urlpatterns = [
    
    path('login/',Login.as_view()),
    
    path('enrolled/', EnrolledView.as_view()),
    path('attend/',Attend.as_view()),
    path('records/',Attend_Record.as_view())
    # path('logout/',logout.as_view()),
]

attendance/attendance/attendance/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('apis.urls')),
    path('',include('faculty.urls')),
]

attendance/attendance/faculty/urls.py
from django.urls import path

from .views import index, login, generateQr, saveAttend

app_name = "faculty"

# urlpatterns
urlpatterns = [
    path("", index, name="index"),
    path("login/", login, name="login"),
    path("generate/", generateQr, name="generateQr"),
    path("save/", saveAttend, name="save"),
]

attendance/attendance/faculty/models.py
from django.db import models

# Create your models here.

attendance/attendance/faculty/views.py
import sys

sys.path.append(".")
from generate import generating
from django.shortcuts import render

sys.path.append("..")
from django.shortcuts import redirect, reverse
from apis.models import Faculty, Sections, Hash, Enrolled
from django.http import HttpResponse, JsonResponse

# Create your views here.


def index(request):
    return render(request, "index.html")


def login(request):

    if request.method == "POST":
        username = request.POST["email"]
        passowrd = request.POST["password"]
        try:

            user = Faculty.objects.get(email=username, password=passowrd)
            lectures_list = Sections.objects.filter(faculty_name=user.Fid)

            context = {"user": user, "lectures_list": lectures_list}

            return render(request, "dashbord.html", context)
        except Faculty.DoesNotExist:
            return redirect(index)


def saveAttend(request):
    count = 0

    if request.method == "POST":

        section_id = request.POST["section_id"]
        total = Enrolled.objects.filter(section_id=section_id)
        attend = Hash.objects.filter(section_id=section_id)
        if len(attend) > 1:
            for i in range(len(total)):
                user = total[i]
                real = attend[i]
                if user.students_id == real.student_id:
                    count += 1
                else:
                    rec = attendace_record.objects.create(
                        students_id=total[i].students_id,
                        section_id=section_id,
                        attend=False,
                    )
                    rec.save()
        else:
            count = 0
        context = {"total_student": len(total), "attended": count}
        return JsonResponse(context)


def generateQr(request):

    if request.method == "POST":
        sid = request.POST["sec_id"]
        try:
            obj = Sections.objects.get(section_id=sid)
        except Sections.DoesNotExist:
            return HttpResponse("Not exist")
        w = generating(sid)
        return HttpResponse(w)

    return HttpResponse("hello")

attendance/attendance/faculty/templates/dashbord.html
<!DOCTYPE html>
<html>

{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Faculty</title>
    <link rel="stylesheet" href='{% static "assets/bootstrap/css/bootstrap.min.css" %}'>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bitter:400,700">
    <link rel="stylesheet" href='{% static "assets/fonts/ionicons.min.css" %}'>
    <link rel="stylesheet" href='{% static "assets/css/Footer-Dark.css" %}'>
    <link rel="stylesheet" href='{% static "assets/css/Header-Dark.css" %}'>
    <link rel="stylesheet" href='{% static "assets/css/Login-Form-Dark.css" %}'>
    <link rel="stylesheet" href='{% static "assets/css/Navigation-Clean.css" %}'>
    <link rel="stylesheet" href='{% static "assets/css/Navigation-with-Button.css" %}'>
    <link rel="stylesheet" href='{% static "assets/css/styles.css" %}'>
</head>

<body>
    <div>
        <div class="header-dark">
            <nav class="navbar navbar-light navbar-expand-md navigation-clean">
                <div class="container"><a class="navbar-brand" href="#">Faculty</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse text-white"
                        id="navcol-1">
                        <ul class="nav navbar-nav ml-auto">
                            <li class="nav-item" role="presentation"><a class="nav-link active text-white" href="#">{{user.name}}</a></li>
                            <li class="nav-item" role="presentation"></li>
                            <li class="nav-item" role="presentation"><a class="nav-link text-white" href="#">LogOut</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
            <div class="container hero">
                <div class="row">
                    <div class="col-md-8 offset-md-2">
                        <h1 class="text-center">WelCome</h1>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col">
                            <div class="form-group text-center">
                                <select class="form-control form-control-lg" style="width: 30%;margin: auto;"  id = "lecture">
                                    <optgroup label="This is a group">
                                        {% for lecture in lectures_list %}
                                        <option value={{ lecture.section_id }}>{{lecture.course_id}} - section {{lecture.section_no}}</option>
                                        {% endfor %}
                                    </optgroup>
                                </select>
                            </div>
                            <div class="form-group text-center">
                                <button class="btn btn-secondary btn-lg text-left" id="btn" type="submit">Start Lecture</button>
                            </div>
                </div>
            </div>
            
                            <p id="attend" style="color: white;"></p>
                            <p id="total" style="color: white;"></p>
        </div>
    </div>
    </div>
    <div class="footer-dark">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Services</h3>
                        <ul>
                            <li><a href="#">Web design</a></li>
                            <li><a href="#">Development</a></li>
                            <li><a href="#">Hosting</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item">
                        <h3>About</h3>
                        <ul>
                            <li><a href="#">Company</a></li>
                            <li><a href="#">Team</a></li>
                            <li><a href="#">Careers</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6 item text">
                        <h3>Company Name</h3>
                        <p>Praesent sed lobortis mi. Suspendisse vel placerat ligula. Vivamus ac sem lacus. Ut vehicula rhoncus elementum. Etiam quis tristique lectus. Aliquam in arcu eget velit pulvinar dictum vel in justo.</p>
                    </div>
                    <div class="col item social"><a href="#"><i class="icon ion-social-facebook"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-instagram"></i></a></div>
                </div>
                <p class="copyright">Company Name © 2017</p>
            </div>
        </footer>
    </div>


    <div class="modal fade bd-example" role="dialog" tabindex="-1" id = 'modal'>
        <div class="modal-dialog " role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Lecture QR</h4><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button></div>
                <div class="modal-body">
                    <img id="imd" src ="../static/2.png">
                </div>
                <div class="modal-footer text-center">
                <button class="btn btn-light" type="button" data-dismiss="modal">Close</button>
                <button class="btn btn-primary" type="button" id = "save-btn">Save</button>
                </div>
            </div>
        </div>
    </div>
    <script src='{% static "assets/js/jquery.min.js" %}'></script>
    <script src='{% static "assets/bootstrap/js/bootstrap.min.js" %}'></script>
    <script> 
    
        
        $('#btn').on('click', function(){
            var sec_id = $("#lecture").val();
            $.ajax({
                url: '{% url "faculty:generateQr" %}',
                method: 'post',
                data: {
                    "sec_id":sec_id,
                    "csrfmiddlewaretoken" : '{{ csrf_token }}'
                },
                success: function (data){
                    $("#imd").attr("src","../static/"+data+".png");
                    $("#modal").modal("show");
                },
                error: function(){

                }
            });
        });

    $('#save-btn').on('click',function(){
        var section_id = $("#lecture").val();
      
        $.ajax({
            url : '{% url "faculty:save" %}',
            method : "post",
            data :{
                "section_id" : section_id,
                "csrfmiddlewaretoken" : '{{ csrf_token }}'
            },
            success : function(data){
                $('#modal').modal('hide');
                document.getElementById("total").innerHTML = data["total_student"];
                document.getElementById("attend").innerHTML = data["attended"];
            },
            error:function(){

            }
        })
    })



    </script>
</body>

</html>

attendance/attendance/faculty/templates/index.html
<!DOCTYPE html>
<html>
    {% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Faculty</title>
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bitter:400,700">
    <link rel="stylesheet" href="{% static 'assets/fonts/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Footer-Dark.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Header-Dark.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Login-Form-Dark.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Navigation-Clean.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Navigation-with-Button.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">
</head>

<body>
    <div class="login-dark">
        <form method="post" action="{% url 'faculty:login'%}">
            {% csrf_token %}
            <h2 class="sr-only">Login Form</h2>
            <div class="illustration"><i class="icon ion-ios-locked-outline"></i></div>
            <div class="form-group"><input class="form-control" type="email" name="email" placeholder="Email"></div>
            <div class="form-group"><input class="form-control" type="password" name="password" placeholder="Password"></div>
            <div class="form-group"><button class="btn btn-primary btn-block" type="submit">Log In</button></div><a class="forgot" href="#">Forgot your email or password?</a></form>
    </div>
    <div class="footer-dark">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Services</h3>
                        <ul>
                            <li><a href="#">Web design</a></li>
                            <li><a href="#">Development</a></li>
                            <li><a href="#">Hosting</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item">
                        <h3>About</h3>
                        <ul>
                            <li><a href="#">Company</a></li>
                            <li><a href="#">Team</a></li>
                            <li><a href="#">Careers</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6 item text">
                        <h3>Company Name</h3>
                        <p>Praesent sed lobortis mi. Suspendisse vel placerat ligula. Vivamus ac sem lacus. Ut vehicula rhoncus elementum. Etiam quis tristique lectus. Aliquam in arcu eget velit pulvinar dictum vel in justo.</p>
                    </div>
                    <div class="col item social"><a href="#"><i class="icon ion-social-facebook"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-instagram"></i></a></div>
                </div>
                <p class="copyright">Company Name © 2017</p>
            </div>
        </footer>
    </div>
    <div></div>
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
</body>

</html>